# Generated by Django 3.0.5 on 2020-04-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentFuzzyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('display_name', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='.')),
                ('vector', models.ManyToManyField(through='photos_ml.EnvironmentFuzzyMembership', to='photos_ml.PhotoEnvironment')),
            ],
        ),
        migrations.AddField(
            model_name='environmentfuzzymembership',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos_ml.PhotoEnvironment'),
        ),
        migrations.AddField(
            model_name='environmentfuzzymembership',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos_ml.Photo'),
        ),
    ]
