# Generated by Django 3.0.5 on 2020-04-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos_ml', '0002_auto_20200426_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
