# Generated by Django 3.0.5 on 2020-05-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos_ml', '0004_photo_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos_ml.ObjectCategory')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos_ml.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='objects',
            field=models.ManyToManyField(through='photos_ml.ObjectIdentification', to='photos_ml.ObjectCategory'),
        ),
    ]
